version: '3.8'

services:
    db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgres/data/
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1347
        - POSTGRES_DB=newtesting
      ports:
          - 5432:5432
    web:
      command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      ports:
        - 8000:8000
      env_file:
        - ./.env
      depends_on:
        - db

    
volumes:
    postgres_data:
networks:
    djangonetwork:
        driver: bridge