# Generated by Django 5.0.1 on 2024-01-29 16:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pre_video_content', models.TextField()),
                ('course_content', models.TextField()),
                ('marketing_content', models.TextField()),
                ('created_at', models.DateField()),
                ('last_modified_at', models.DateField()),
                ('course_type', models.CharField(max_length=50)),
                ('certification_avaliable', models.BooleanField()),
                ('fees', models.CharField(max_length=50)),
                ('plan_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=18)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('zipcode', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('profile_image', models.URLField(max_length=250)),
                ('total_reviews', models.CharField(max_length=10)),
                ('courses_taught', models.ManyToManyField(to='API.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('profileImage', models.URLField(max_length=250)),
                ('billinginfo', models.CharField(max_length=200)),
                ('subscription', models.CharField(max_length=200)),
                ('fees_amount_paid', models.CharField(max_length=30)),
                ('payment_method', models.CharField(max_length=30)),
                ('wishlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
                ('courses_enrolled', models.ManyToManyField(to='API.courses')),
            ],
        ),
    ]
