# Generated by Django 5.0.1 on 2024-02-06 10:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='billinginfo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='fees_amount_paid',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='profileImage',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='students',
            name='subscription',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='wishlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default='', size=10),
        ),
    ]
