# Generated by Django 5.0.1 on 2024-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_students_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='profile_image',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='total_reviews',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
