# Generated by Django 5.0.1 on 2024-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_instructors_address_alter_instructors_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='password',
            field=models.CharField(max_length=400),
        ),
    ]
