# Generated by Django 5.0.1 on 2024-02-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_instructors_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_video',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor_id',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
